import { writeFile } from 'node:fs/promises';

const channelId = 'UCiz2f9aRYacg18UfVw7ZLJw';
const channelUrl = 'https://www.youtube.com/@bahaa_aldeen_nawlo';
const feedUrl = `https://www.youtube.com/feeds/videos.xml?channel_id=${channelId}`;
const outputPath = new URL('../src/data/youtube.ts', import.meta.url);

function decodeXml(value = '') {
  return value
    .replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, '$1')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .trim();
}

function readTag(entry, tag) {
  const match = entry.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)</${tag}>`));
  return decodeXml(match?.[1]);
}

const response = await fetch(feedUrl, {
  headers: { 'user-agent': 'Bahaa-Aldeen-Nawlo-Portfolio/1.0' },
});

if (!response.ok) {
  throw new Error(`YouTube RSS request failed: ${response.status}`);
}

const xml = await response.text();
const videos = [...xml.matchAll(/<entry>([\s\S]*?)<\/entry>/g)].map((match) => {
  const entry = match[1];
  const id = readTag(entry, 'yt:videoId');

  return {
    title: readTag(entry, 'title'),
    url: `https://www.youtube.com/watch?v=${id}`,
    thumbnail: `https://i.ytimg.com/vi/${id}/hqdefault.jpg`,
    date: readTag(entry, 'published').slice(0, 10),
    description: readTag(entry, 'media:description'),
  };
});

const output = `// Generated by scripts/sync-youtube.mjs. Do not edit manually.\nexport interface YoutubeVideo {\n  title: string;\n  url: string;\n  thumbnail: string;\n  date: string;\n  description: string;\n}\n\nexport const YOUTUBE_VIDEOS: YoutubeVideo[] = ${JSON.stringify(videos, null, 2)};\n\nexport const YOUTUBE_CHANNEL_URL = '${channelUrl}';\n`;

await writeFile(outputPath, output);
console.log(`Synchronized ${videos.length} YouTube videos.`);